version: '3.8'

services:
  camunda:
    build: ./camunda
    container_name: camunda-bpm
    ports:
      - '8080:8080'

  webapp:
    build: ./webapp
    container_name: webapp
    depends_on:
      - camunda
      - mongodb
      - backend
    ports:
      - '80:80'
    environment:
      - BACKEND_BASE_URL=http://backend:8081

  backend:
    build: ./backend
    container_name: express-app
    command: npm start
    restart: on-failure
    ports:
      - '8081:5000'
    environment:
      - PORT=5000
      - CAMUNDA_API_BASE_URL=http://camunda:8080/engine-rest
    depends_on:
      - camunda
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db

  notification:
    build: ./notification-service
    container_name: notification-service
    command: npm start
    restart: always
    ports:
      - 8082:7000
    environment:
      - CAMUNDA_API_BASE_URL=http://camunda:8080/engine-rest
      - WEBHOOK_PORT=7000
