export const QUERY_KEYS = {
  GET_PROCESSES: 'GET_PROCESSES',
  GET_PROCESS_DEFINITION: 'GET_PROCESS_DEFINITION',
  GET_USERS: 'GET_USERS',
};

export const BACKEND_BASE_URL = 'http://localhost:8081';
