export const QUERY_KEYS = {
  GET_PROCESSES: 'GET_PROCESSES',
  GET_PROCESS_DEFINITION: 'GET_PROCESS_DEFINITION',
  GET_USERS: 'GET_USERS',
  GET_EMPLOYEE_TASKS: 'GET_EMPLOYEE_TASKS',
  GET_SITES_LIST: 'GET_SITES_LIST',
};

export const BACKEND_BASE_URL = 'http://localhost:8081';
